name: SLAC_Xopt
channels:
  - conda-forge
  - gpytorch
  - pytorch
  - defaults
dependencies:
  - argon2-cffi=21.3.0=pyhd8ed1ab_0
  - argon2-cffi-bindings=21.2.0=py39hb82d6ee_1
  - asttokens=2.0.5=pyhd8ed1ab_0
  - attrs=21.4.0=pyhd8ed1ab_0
  - backcall=0.2.0=pyh9f0ad1d_0
  - backports=1.0=py_2
  - backports.functools_lru_cache=1.6.4=pyhd8ed1ab_0
  - black=22.1.0=pyhd8ed1ab_0
  - blas=2.113=mkl
  - blas-devel=3.9.0=13_win64_mkl
  - bleach=4.1.0=pyhd8ed1ab_0
  - botorch=0.6.0=pyhd8ed1ab_0
  - bzip2=1.0.8=h8ffe710_4
  - ca-certificates=2021.10.8=h5b45459_0
  - cffi=1.15.0=py39h0878f49_0
  - click=8.0.3=py39hcbf5309_1
  - colorama=0.4.4=pyh9f0ad1d_0
  - cudatoolkit=11.1.1=heb2d755_10
  - dataclasses=0.8=pyhc8e2a94_3
  - deap=1.3.1=py39h2e25243_3
  - debugpy=1.5.1=py39h415ef7b_0
  - decorator=5.1.1=pyhd8ed1ab_0
  - defusedxml=0.7.1=pyhd8ed1ab_0
  - entrypoints=0.4=pyhd8ed1ab_0
  - executing=0.8.2=pyhd8ed1ab_0
  - flit-core=3.6.0=pyhd8ed1ab_0
  - gpytorch=1.6.0=pyhd8ed1ab_1
  - icu=68.2=h0e60522_0
  - importlib-metadata=4.10.1=py39hcbf5309_0
  - importlib_resources=5.4.0=pyhd8ed1ab_0
  - intel-openmp=2022.0.0=h57928b3_3663
  - ipykernel=6.8.0=py39h832f523_0
  - ipython=8.0.1=py39hcbf5309_0
  - ipython_genutils=0.2.0=py_1
  - ipywidgets=7.6.5=pyhd8ed1ab_0
  - jedi=0.18.1=py39hcbf5309_0
  - jinja2=3.0.3=pyhd8ed1ab_0
  - jpeg=9e=h8ffe710_0
  - jsonschema=4.4.0=pyhd8ed1ab_0
  - jupyter=1.0.0=py39hcbf5309_7
  - jupyter_client=7.1.2=pyhd8ed1ab_0
  - jupyter_console=6.4.0=pyhd8ed1ab_0
  - jupyter_core=4.9.1=py39hcbf5309_1
  - jupyterlab_pygments=0.1.2=pyh9f0ad1d_0
  - jupyterlab_widgets=1.0.2=pyhd8ed1ab_0
  - libblas=3.9.0=13_win64_mkl
  - libcblas=3.9.0=13_win64_mkl
  - libclang=11.1.0=default_h5c34c98_1
  - libffi=3.4.2=h8ffe710_5
  - liblapack=3.9.0=13_win64_mkl
  - liblapacke=3.9.0=13_win64_mkl
  - libpng=1.6.37=h1d00b33_2
  - libsodium=1.0.18=h8d14728_1
  - libuv=1.43.0=h8ffe710_0
  - libzlib=1.2.11=h8ffe710_1013
  - m2w64-gcc-libgfortran=5.3.0=6
  - m2w64-gcc-libs=5.3.0=7
  - m2w64-gcc-libs-core=5.3.0=7
  - m2w64-gmp=6.1.0=2
  - m2w64-libwinpthread-git=5.0.0.4634.697f757=2
  - markupsafe=2.0.1=py39hb82d6ee_1
  - matplotlib-inline=0.1.3=pyhd8ed1ab_0
  - mistune=0.8.4=py39hb82d6ee_1005
  - mkl=2022.0.0=h0e2418a_796
  - mkl-devel=2022.0.0=h57928b3_797
  - mkl-include=2022.0.0=h0e2418a_796
  - msys2-conda-epoch=20160418=1
  - mypy_extensions=0.4.3=py39hcbf5309_4
  - nbclient=0.5.10=pyhd8ed1ab_1
  - nbconvert=6.4.1=py39hcbf5309_0
  - nbformat=5.1.3=pyhd8ed1ab_0
  - nest-asyncio=1.5.4=pyhd8ed1ab_0
  - notebook=6.4.8=pyha770c72_0
  - numpy=1.22.1=py39h6331f09_0
  - openssl=1.1.1l=h8ffe710_0
  - packaging=21.3=pyhd8ed1ab_0
  - pandas=1.4.0=py39h2e25243_0
  - pandoc=2.17.1.1=h57928b3_0
  - pandocfilters=1.5.0=pyhd8ed1ab_0
  - parso=0.8.3=pyhd8ed1ab_0
  - pathspec=0.9.0=pyhd8ed1ab_0
  - pickleshare=0.7.5=py_1003
  - pip=22.0.3=pyhd8ed1ab_0
  - platformdirs=2.3.0=pyhd8ed1ab_0
  - prometheus_client=0.13.1=pyhd8ed1ab_0
  - prompt-toolkit=3.0.26=pyha770c72_0
  - prompt_toolkit=3.0.26=hd8ed1ab_0
  - pure_eval=0.2.2=pyhd8ed1ab_0
  - pycparser=2.21=pyhd8ed1ab_0
  - pygments=2.11.2=pyhd8ed1ab_0
  - pyparsing=3.0.7=pyhd8ed1ab_0
  - pyqt=5.12.3=py39hcbf5309_8
  - pyqt-impl=5.12.3=py39h415ef7b_8
  - pyqt5-sip=4.19.18=py39h415ef7b_8
  - pyqtchart=5.12=py39h415ef7b_8
  - pyqtwebengine=5.12.1=py39h415ef7b_8
  - pyrsistent=0.18.1=py39hb82d6ee_0
  - python=3.9.10=h9a09f29_2_cpython
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python_abi=3.9=2_cp39
  - pytorch=1.10.2=py3.9_cuda11.1_cudnn8_0
  - pytorch-mutex=1.0=cuda
  - pytz=2021.3=pyhd8ed1ab_0
  - pywin32=303=py39hb82d6ee_0
  - pywinpty=2.0.1=py39h99910a6_0
  - pyyaml=6.0=py39hb82d6ee_3
  - pyzmq=22.3.0=py39he46f08e_1
  - qt=5.12.9=h5909a2a_4
  - qtconsole=5.2.2=pyhd8ed1ab_1
  - qtconsole-base=5.2.2=pyhd8ed1ab_1
  - qtpy=2.0.1=pyhd8ed1ab_0
  - scipy=1.7.3=py39hc0c34ad_0
  - send2trash=1.8.0=pyhd8ed1ab_0
  - setuptools=60.7.1=py39hcbf5309_0
  - six=1.16.0=pyh6c4a22f_0
  - sqlite=3.37.0=h8ffe710_0
  - stack_data=0.1.4=pyhd8ed1ab_0
  - tbb=2021.5.0=h2d74725_0
  - terminado=0.13.1=py39hcbf5309_0
  - testpath=0.5.0=pyhd8ed1ab_0
  - tk=8.6.11=h8ffe710_1
  - tomli=2.0.0=pyhd8ed1ab_1
  - tornado=6.1=py39hb82d6ee_2
  - tqdm=4.62.3=pyhd8ed1ab_0
  - traitlets=5.1.1=pyhd8ed1ab_0
  - typed-ast=1.5.2=py39hb82d6ee_0
  - typing_extensions=4.0.1=pyha770c72_0
  - tzdata=2021e=he74cb21_0
  - ucrt=10.0.20348.0=h57928b3_0
  - vc=14.2=hb210afc_6
  - vs2015_runtime=14.29.30037=h902a5da_6
  - wcwidth=0.2.5=pyh9f0ad1d_2
  - webencodings=0.5.1=py_1
  - wheel=0.37.1=pyhd8ed1ab_0
  - widgetsnbextension=3.5.2=py39hcbf5309_1
  - winpty=0.4.3=4
  - xopt=0.5.0=pyhd8ed1ab_0
  - xz=5.2.5=h62dcd97_1
  - yaml=0.2.5=h8ffe710_2
  - zeromq=4.3.4=h0e60522_1
  - zipp=3.7.0=pyhd8ed1ab_1
  - zlib=1.2.11=h8ffe710_1013
  - pip:
    - pyepics==3.5.1
prefix: C:\ProgramData\Miniconda3\envs\SLAC_Xopt
